name: Run on release published
on:
  push:
    tags:
      - "*"
jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello world
        run: echo hello world
